shut up adb

diff --git a/system/core/adb/launch_adbd b/system/core/adb/launch_adbd
--- a/system/core/adb/launch_adbd
+++ b/system/core/adb/launch_adbd
@@ -34,24 +34,25 @@ if [ -f /etc/default/adbd ]; then
         . /etc/default/adbd
 fi
 echo -n "Starting adbd:  " > /dev/kmsg
-start-stop-daemon -S -b -a /sbin/adbd
+start-stop-daemon -S -b -a /sbin/adbd || true
 # Check first if the /etc/adb_devid already has an id saved from earlier boot up.
 # If yes use it to retrieve adb devices else use the msm ID and save it to /etc/adb_devid for subsequent boot ups.
-if [ -s "/etc/adb_devid" ]
-then
-      cat /etc/adb_devid > /sys/class/android_usb/android0/iSerial
-else
-      ret_val=`cat /proc/cmdline | grep "androidboot.serialno" |wc -l`
+# fails because readonly fs
+# if [ -s "/etc/adb_devid" ]
+# then
+#       cat /etc/adb_devid > /sys/class/android_usb/android0/iSerial
+# else
+#       ret_val=`cat /proc/cmdline | grep "androidboot.serialno" |wc -l`
 
-if  [ $ret_val -eq 1 ]
-then
-    serial_no=`cat /proc/cmdline | awk '{ for ( n=1; n<=NF; n++ ) if($n ~ "androidboot.serial") print $n }' | awk '{split($0,a, "=");print a[2]}'`
-    echo $serial_no > /sys/class/android_usb/android0/iSerial
-else
-    cat /proc/sys/kernel/random/boot_id | cut -d- -f5 > /sys/class/android_usb/android0/iSerial
-fi
-    cat /sys/class/android_usb/android0/iSerial > /etc/adb_devid
-    sync
-fi
+# if  [ $ret_val -eq 1 ]
+# then
+#     serial_no=`cat /proc/cmdline | awk '{ for ( n=1; n<=NF; n++ ) if($n ~ "androidboot.serial") print $n }' | awk '{split($0,a, "=");print a[2]}'`
+#     echo $serial_no > /sys/class/android_usb/android0/iSerial
+# else
+#     cat /proc/sys/kernel/random/boot_id | cut -d- -f5 > /sys/class/android_usb/android0/iSerial
+# fi
+#     cat /sys/class/android_usb/android0/iSerial > /etc/adb_devid
+#     sync
+# fi
 echo "done"
 exit 0
